// 初始化kylin页面信息
export const INIT_KYLIN_INFO = 'INIT_KYLIN_INFO';
// 加载初始化信息
export const LOAD_INIT_INFO = 'LOAD_INIT_INFO';
// 根据选中cube设置查询条件(度量,维度..)
export const SET_PAGE_QUERY_INFO_BY_SELECT_CUBE = 'SET_PAGE_QUERY_INFO_BY_SELECT_CUBE';
// 根据用户选择条件添加查询条件
export const SET_QUERY_INFO_BY_USER_OPERATE = 'SET_QUERY_INFO_BY_USER_OPERATE';
// 查询数据按钮控制
export const QUERY_BUTTON_CONTROL = 'QUERY_BUTTON_CONTROL';
// 生成下载文件按钮控制
export const GENERATE_FILE_BUTTON_CONTROL = 'GENERATE_FILE_BUTTON_CONTROL';
// 展示下载文件列表
export const SHOW_DOWNLOAD_FILES = 'SHOW_DOWNLOAD_FILES';
// 查询结果渲染table
export const QUERY_RESULT_RENDER_TABLE = 'QUERY_RESULT_RENDER_TABLE';
// loading状态控制
export const QUERY_LOADING_CONTROL = 'QUERY_LOADING_CONTROL';
// 添加用户自定义查询条件
export const ADD_CUSTOMIZED_DEFINITION_CONDITION = 'ADD_CUSTOMIZED_DEFINITION_CONDITION';
// 登录验证
export const LOGIN_AUTHENTICATION = 'LOGIN_AUTHENTICATION';
// 登出
export const LOGIN_LOGUOT = 'LOGIN_LOGUOT';
// 展示配置信息
export const KYLINCONFIG_SHOW_CONFIG_INFO = 'KYLINCONFIG_SHOW_CONFIG_INFO';
// 逐条编辑配置信息
export const KYLINCONFIG_EDIT_CONFIG_INFO = 'KYLINCONFIG_EDIT_CONFIG_INFO';
// 删除配置信息
export const KYLINCONFIG_DELETE_CONFIG_INFO = 'KYLINCONFIG_DELETE_CONFIG_INFO';
// 新增一条配置信息
export const KYLINCONFIG_NEW_CONFIG_INFO = 'KYLINCONFIG_NEW_CONFIG_INFO';
// 设置form信息
export const KYLINCONFIG_SET_FORM_INFO = 'KYLINCONFIG_SET_FORM_INFO';
// 新增操作,清空form表格
export const KYLINCONFIG_CLEAR_FORM = 'KYLINCONFIG_CLEAR_FORM';
// 选择待配置cube
export const SELECT_PEDDING_CUBE = 'SELECT_PEDDING_CUBE';
// 删除用户自定义条件
export const DELETE_USER_DEFINED_TERM = 'DELETE_USER_DEFINED_TERM';
// 重置当前用户自定义条件(针对用户当前手动删除操作)
export const RESET_USER_DEFINED_TERM = 'RESET_USER_DEFINED_TERM';
// 页面菜单显示控制
export const QUERY_PAGEMENU_CONTROL = 'QUERY_PAGEMENU_CONTROL';
